blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/KelTech-Services/PlexRoulette/discussions
    about: Ask questions or start a discussion about PlexRoulette
